version: '2.17'

services:
  database:
    container_name: fm-mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fmdb
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - fm-mysql:/var/lib/mysql

volumes:
  fm-mysql:
    driver: local

networks:
  fm-mysql:
    driver: bridge
